name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.4'
          cache: true
      - run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
